spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myBatis
    username: root
    password: <password>
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: com.example.demo.model
  mapper-locations: classpath*:**/mappers/*.xml
